---
title: "GIS_ShpToGeoJSON"
---

**Autor:** Katharina Kaelin 

**Stand:** 19.05.2020

**Beschreibung:** 

**Auswertungshinweis:**

**Metadatenhinweis:**

# R setup

```{r setup}

# clear R memory
# rm(list = ls())

# db_connect.r
source("P:/db_connect.r")

# import libraries
library(sf)
library(lwgeom)
library(rmapshaper)

options(scipen = 1000000)
options(digits = 6)

# values of the environment variables.
Sys.getenv()

```

# import shp

```{r}

# Primarstufe
ps_2020 <- sf::st_read("L:/STAT/08_DS/03_GIS/Geodaten/2020/PS_SCHULGEMEINDEN_SHAPE_F_KTZH_2020.shp", stringsAsFactors = FALSE, crs=2056)
ps_2019 <- sf::st_read("L:/STAT/08_DS/03_GIS/Geodaten/2019/PS_SCHULGEMEINDEN_SHAPE_F_KTZH_2019.shp", stringsAsFactors = FALSE, crs=2056)

# Oberstufe
os_2020 <- sf::st_read("L:/STAT/08_DS/03_GIS/Geodaten/2020/OS_SCHULGEMEINDEN_SHAPE_F_KTZH_2020.shp", stringsAsFactors = FALSE, crs=2056)
os_2019 <- sf::st_read("L:/STAT/08_DS/03_GIS/Geodaten/2019/OS_SCHULGEMEINDEN_SHAPE_F_KTZH_2019.shp", stringsAsFactors = FALSE, crs=2056)

# GrosseSee
see <- sf::st_read("L:/STAT/08_DS/03_GIS/Geodaten/2020/GrosseSee_gen_F_KTZH_2020.shp", stringsAsFactors = FALSE, crs=2056)

```

# generalize

```{r}

# Primarstufe
ps_2020_gen_temp <- rmapshaper::ms_simplify(ps_2020, keep = 0.01, keep_shapes = TRUE)
ps_2020_gen <- lwgeom::st_snap_to_grid(ps_2020_gen_temp,1)

ps_2019_gen_temp <- rmapshaper::ms_simplify(ps_2019, keep = 0.01, keep_shapes = TRUE)
ps_2019_gen <- lwgeom::st_snap_to_grid(ps_2019_gen_temp,1)

# Oberstufe
os_2020_gen_temp <- rmapshaper::ms_simplify(os_2020, keep = 0.01, keep_shapes = TRUE)
os_2020_gen <- lwgeom::st_snap_to_grid(os_2020_gen_temp,1)

os_2019_gen_temp <- rmapshaper::ms_simplify(os_2019, keep = 0.01, keep_shapes = TRUE)
os_2019_gen <- lwgeom::st_snap_to_grid(os_2019_gen_temp,1)

# GrosseSee
see_gen_temp1 <- rmapshaper::ms_simplify(see, keep = 0.25, keep_shapes = TRUE)
see_gen_temp2 <- lwgeom::st_snap_to_grid(see_gen_temp1,1)
see_gen<- st_buffer(see_gen_temp2, dist = 150) %>% dplyr::select()
plot(st_geometry(see_gen))
#st_write(see_gen, "P:/KK_Temp/Test.shp", delete_layer = TRUE)

```

# add see

```{r}

see_gen_sel <- see_gen %>% `is.na<-` (names(ps_2020_gen)) %>% st_set_geometry(st_geometry(see_gen))  
ps_see_2020_gen <- st_difference(ps_2020_gen, st_union(see_gen)) %>% rbind(see_gen_sel) %>% mutate(ART_N = ifelse(is.na(SGEM_CODE), "See", "Schulgemeinde"))

see_gen_sel <- see_gen %>% `is.na<-` (names(ps_2019_gen)) %>% st_set_geometry(st_geometry(see_gen)) 
ps_see_2019_gen <- st_difference(ps_2019_gen, st_union(see_gen)) %>% rbind(see_gen_sel) %>% mutate(ART_N = ifelse(is.na(SGEM_CODE), "See", "Schulgemeinde"))

see_gen_sel <- see_gen %>% `is.na<-` (names(os_2020_gen)) %>% st_set_geometry(st_geometry(see_gen)) 
os_see_2020_gen <- st_difference(os_2020_gen, st_union(see_gen)) %>% rbind(see_gen_sel) %>% mutate(ART_N = ifelse(is.na(SGEM_CODE), "See", "Schulgemeinde"))

see_gen_sel <- see_gen %>% `is.na<-` (names(os_2019_gen)) %>% st_set_geometry(st_geometry(see_gen)) 
os_see_2019_gen <- st_difference(os_2019_gen, st_union(see_gen)) %>% rbind(see_gen_sel) %>% mutate(ART_N = ifelse(is.na(SGEM_CODE), "See", "Schulgemeinde"))

```


# export GeoJSON

```{r}

# Primarstufe

## eps2056

path_2056 = "C:/gitrepos/Ressources_Maps/2020/PS_SCHULGEMEINDEN_SHAPE_gen_epsg2056_F_KTZH_2020.json"
file.remove(path_2056)
sf::st_write(ps_see_2020_gen, path_2056, driver="GeoJSON")

path_2056 = "C:/gitrepos/Ressources_Maps/2019/PS_SCHULGEMEINDEN_SHAPE_gen_epsg2056_F_KTZH_2019.json"
file.remove(path_2056)
sf::st_write(ps_see_2019_gen, path_2056, driver="GeoJSON")

## eps4326

path_4326 = "C:/gitrepos/Ressources_Maps/2020/PS_SCHULGEMEINDEN_SHAPE_gen_epsg4326_F_KTZH_2020.json"
file.remove(path_4326)
sf::st_write(ps_see_2020_gen %>% st_transform(4326), path_4326, driver="GeoJSON")

path_4326 = "C:/gitrepos/Ressources_Maps/2019/PS_SCHULGEMEINDEN_SHAPE_gen_epsg4326_F_KTZH_2019.json"
file.remove(path_4326)
sf::st_write(ps_see_2019_gen %>% st_transform(4326), path_4326, driver="GeoJSON")

# Oberstufe

## eps2056

path_2056 = "C:/gitrepos/Ressources_Maps/2020/OS_SCHULGEMEINDEN_SHAPE_gen_epsg2056_F_KTZH_2020.json"
file.remove(path_2056)
sf::st_write(os_see_2020_gen, path_2056, driver="GeoJSON")

path_2056 = "C:/gitrepos/Ressources_Maps/2019/OS_SCHULGEMEINDEN_SHAPE_gen_epsg2056_F_KTZH_2019.json"
file.remove(path_2056)
sf::st_write(os_see_2019_gen, path_2056, driver="GeoJSON")

## eps4326

path_4326 = "C:/gitrepos/Ressources_Maps/2020/OS_SCHULGEMEINDEN_SHAPE_gen_epsg4326_F_KTZH_2020.json"
file.remove(path_4326)
sf::st_write(os_see_2020_gen %>% st_transform(4326), path_4326, driver="GeoJSON")

path_4326 = "C:/gitrepos/Ressources_Maps/2019/OS_SCHULGEMEINDEN_SHAPE_gen_epsg4326_F_KTZH_2020.json"
file.remove(path_4326)
sf::st_write(os_see_2019_gen %>% st_transform(4326), path_4326, driver="GeoJSON")


```





